workflows:
  android-build:
    name: BlueConnect ROHD Codemagic Build
    max_build_duration: 20
    environment:
      java: 17
    scripts:
      - name: Grant execute permission
        script: chmod +x gradlew
      - name: Assemble Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - ROHD@blueconnect.ro
